[test]
levels = ["syntax", "javascript", "install", "registration", "instantiation", "execution"]

[test.workflows]
# cpu = ["360_render","cpu_plane_segmentation", "cpu_depth_normal_conditioned", "pano_crop", "pano_info", "panorama_shift", "preview_panorama", "test_wrap_unwrap","cpu_depth_merge_mesh_pointcloud"]
cpu = ["360_render", "pano_crop", "pano_info", "panorama_shift", "preview_panorama", "test_wrap_unwrap"]
cuda = ["gpu_plane_segmentation", "gpu_depth_normal_conditioned","gpu_depth_merge_mesh_pointcloud"]

[test.platforms]
platforms = ["linux", "macos", "windows", "windows_portable", "macos_desktop", "windows_desktop", "linux_cuda", "windows_cuda", "windows_portable_cuda", "windows_desktop_cuda"]
