"""ComfyUI-PanoPack — aggregated node registry."""

from .panorama_type import (
    NODE_CLASS_MAPPINGS as TYPE_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as TYPE_DISP,
)
from .panorama_info import (
    NODE_CLASS_MAPPINGS as INFO_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as INFO_DISP,
)
from .panorama_shift import (
    NODE_CLASS_MAPPINGS as SHIFT_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as SHIFT_DISP,
)
from .panorama_split import (
    NODE_CLASS_MAPPINGS as SPLIT_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as SPLIT_DISP,
)
from .panorama_cube_split import (
    NODE_CLASS_MAPPINGS as CUBE_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as CUBE_DISP,
)
from .panorama_viewer import (
    NODE_CLASS_MAPPINGS as VIEWER_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as VIEWER_DISP,
)
from .plane_segment import (
    NODE_CLASS_MAPPINGS as PLANE_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as PLANE_DISP,
)
from .depth_merge import (
    NODE_CLASS_MAPPINGS as DEPTH_MERGE_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as DEPTH_MERGE_DISP,
)
from .build_point_cloud import (
    NODE_CLASS_MAPPINGS as POINT_CLOUD_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as POINT_CLOUD_DISP,
)
from .build_mesh import (
    NODE_CLASS_MAPPINGS as MESH_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as MESH_DISP,
)
from .panorama_crop import (
    NODE_CLASS_MAPPINGS as CROP_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as CROP_DISP,
)
from .pano_render_gaussians import (
    NODE_CLASS_MAPPINGS as RENDER_GAUSS_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as RENDER_GAUSS_DISP,
)
from .pano_render_mesh import (
    NODE_CLASS_MAPPINGS as RENDER_MESH_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as RENDER_MESH_DISP,
)
from .panorama_split_adaptive import (
    NODE_CLASS_MAPPINGS as SPLIT_ADAPTIVE_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as SPLIT_ADAPTIVE_DISP,
)
from .extract_largest_mask import (
    NODE_CLASS_MAPPINGS as LARGEST_MASK_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as LARGEST_MASK_DISP,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(TYPE_MAPS)
NODE_CLASS_MAPPINGS.update(INFO_MAPS)
NODE_CLASS_MAPPINGS.update(SHIFT_MAPS)
NODE_CLASS_MAPPINGS.update(SPLIT_MAPS)
NODE_CLASS_MAPPINGS.update(CUBE_MAPS)
NODE_CLASS_MAPPINGS.update(VIEWER_MAPS)
NODE_CLASS_MAPPINGS.update(PLANE_MAPS)
NODE_CLASS_MAPPINGS.update(DEPTH_MERGE_MAPS)
NODE_CLASS_MAPPINGS.update(POINT_CLOUD_MAPS)
NODE_CLASS_MAPPINGS.update(MESH_MAPS)
NODE_CLASS_MAPPINGS.update(CROP_MAPS)
NODE_CLASS_MAPPINGS.update(RENDER_GAUSS_MAPS)
NODE_CLASS_MAPPINGS.update(RENDER_MESH_MAPS)
NODE_CLASS_MAPPINGS.update(SPLIT_ADAPTIVE_MAPS)
NODE_CLASS_MAPPINGS.update(LARGEST_MASK_MAPS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(TYPE_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(INFO_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(SHIFT_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(SPLIT_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(CUBE_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(VIEWER_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(PLANE_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(DEPTH_MERGE_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(POINT_CLOUD_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(MESH_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(CROP_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(RENDER_GAUSS_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(RENDER_MESH_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(SPLIT_ADAPTIVE_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(LARGEST_MASK_DISP)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
