"""ComfyUI-PanoPack — aggregated node registry."""

from .panorama_type import (
    NODE_CLASS_MAPPINGS as TYPE_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as TYPE_DISP,
)
from .panorama_info import (
    NODE_CLASS_MAPPINGS as INFO_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as INFO_DISP,
)
from .panorama_shift import (
    NODE_CLASS_MAPPINGS as SHIFT_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as SHIFT_DISP,
)
from .panorama_viewer import (
    NODE_CLASS_MAPPINGS as VIEWER_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as VIEWER_DISP,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(TYPE_MAPS)
NODE_CLASS_MAPPINGS.update(INFO_MAPS)
NODE_CLASS_MAPPINGS.update(SHIFT_MAPS)
NODE_CLASS_MAPPINGS.update(VIEWER_MAPS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(TYPE_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(INFO_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(SHIFT_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(VIEWER_DISP)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
